### ISSUE TITLE
Revise preferred ways of communication in FAQ

### ISSUE THREAD

**Issue by mdrost** [laravel-notification-channels/laravel-notification-channels.github.io#11]
The FAQ says:
>Things you should be knowing:
If you need help with anything just ask us. We're nice guys.
[Freek Van der Herten](https://twitter.com/freekmurze)
[Mohamed Said](https://twitter.com/themsaid)
[Marcel Pociot](https://twitter.com/marcelpociot)

ans it links to maintainers Twitters. However Freek Van der Herten in his last [tweet](https://twitter.com/freekmurze/status/855005329163247620) says:
>Friendly suggestion: never email package maintainers directly with questions, always use the issue tracker on Github

So it is not clear what to do with long waiting pull requests. Should I use twitter, open issue or ping someone (@freekmurze @themsaid @mpociot)?

**Comment by themsaid** [comment]
Howdy, sorry :) Looking into the PRs during the weekend.

**Comment by mdrost** [comment]
Are there any progress?

**Comment by themsaid** [comment]
@mdrost I just emailed you an invitation to https://github.com/laravel-notification-channels/sms-api

**Comment by themsaid** [comment]
When you're ready let me know to setup packagist and update the website.

**Comment by mdrost** [comment]
@themsaid I am ready.
