### ISSUE TITLE
Notification Channel Updates

### ISSUE THREAD

**Issue by atymic** [laravel-notification-channels/laravel-notification-channels.github.io#16]
Hey 🙂

I've noticed that the notification channels repos/site have a fair few pending issues, PRs, etc.

I was wondering if you would like some help to get everything up to date. A lot of the packages are missing support for new laravel versions, and there are services that are broken on no longer exist. 

I'm happy to do this via PRs, if you are open to contributions.

Thanks 😄

**Comment by atymic** [comment]
cc @mpociot @themsaid @freekmurze 
(sorry in advance for the ping)

**Comment by freekmurze** [comment]
I don’t have time to look into the issues of this github org anymore. If @mpociot and @themsaid agree, I could give you admin rights so you can make fixes across the repos.

**Comment by atymic** [comment]
I'd be happy to either do it via PR or directly, up to you guys.
Thanks for the reply :)

**Comment by freekmurze** [comment]
Feel free to make improvements directly 👍

**Comment by atymic** [comment]
Thanks :)
I'll get started soon!

**Comment by freekmurze** [comment]
👍👍👍

**Comment by atymic** [comment]
Hey @freekmurze 

I was wondering if you had contact with Mohamed (themsaid)?
A lot of the repo have broken packagist webhooks, and it means we can't release any new channels or update existing ones to Laravel 6.

I've tried emailing him, tagging him in issues and `@ing` him on twitter without success.

Thanks :) 

Some examples:
https://github.com/laravel-notification-channels/bearychat/issues/12
https://github.com/laravel-notification-channels/webhook/issues/29
https://github.com/laravel-notification-channels/apn/issues/62
https://github.com/laravel-notification-channels/webpush/issues/100
https://github.com/laravel-notification-channels/messagebird/issues/23
