### ISSUE TITLE
How to add new channel

### ISSUE THREAD

**Issue by ElfSundae** [laravel-notification-channels/laravel-notification-channels.github.io#7]
Do I need to send a PR to gh-pages-source ? 

service: BearyChat
website: https://bearychat.com
intro: A messenger for teams.
channel: https://github.com/laravel-notification-channels/bearychat

**Comment by mpociot** [comment]
I'll add it in an hour :)

Elf Sundae notifications@github.com schrieb am Mo., 29. Aug. 2016, 7:53
vorm.:

**Comment by ElfSundae** [comment]
Thank you very much.

**Comment by mpociot** [comment]
Done: http://laravel-notification-channels.com/bearychat/
